export const translations = {
  en: {
    title: "GigShield AI",
    subtitle: "AI-powered income protection",
    protected: "Protected Earnings",
    live: "LIVE PROTECTION ACTIVE",
    monitoring: "Real-time monitoring active",
    risk: "Risk Engine",
    disruption: "Heavy Rain Disruption Detected",
    premium: "Smart Premium",
    update: "UPDATE AI PREMIUM",
    trigger: "TRIGGER EVENT",
    payout: "Instant Payout",
    awaiting: "Awaiting disruption trigger...",
    credited: "credited instantly",
  },

  hi: {
    title: "GigShield AI",
    subtitle: "AI आधारित आय सुरक्षा",
    protected: "सुरक्षित कमाई",
    live: "सुरक्षा सक्रिय है",
    monitoring: "रियल-टाइम मॉनिटरिंग",
    risk: "जोखिम इंजन",
    disruption: "भारी बारिश का पता चला",
    premium: "स्मार्ट प्रीमियम",
    update: "प्रीमियम अपडेट करें",
    trigger: "इवेंट ट्रिगर करें",
    payout: "तुरंत भुगतान",
    awaiting: "ट्रिगर का इंतजार...",
    credited: "तुरंत जमा",
  },

  mr: {
    title: "GigShield AI",
    subtitle: "AI आधारित उत्पन्न संरक्षण",
    protected: "संरक्षित कमाई",
    live: "संरक्षण सक्रिय आहे",
    monitoring: "रिअल-टाइम मॉनिटरिंग",
    risk: "जोखीम इंजिन",
    disruption: "जोरदार पाऊस आढळला",
    premium: "स्मार्ट प्रीमियम",
    update: "प्रीमियम अपडेट करा",
    trigger: "इव्हेंट ट्रिगर करा",
    payout: "त्वरित पेमेंट",
    awaiting: "ट्रिगरची वाट पाहत आहे...",
    credited: "ताबडतोब जमा",
  },

  ta: {
    title: "GigShield AI",
    subtitle: "AI வருமான பாதுகாப்பு",
    protected: "பாதுகாக்கப்பட்ட வருமானம்",
    live: "பாதுகாப்பு செயலில் உள்ளது",
    monitoring: "நேரடி கண்காணிப்பு",
    risk: "ஆபத்து இயந்திரம்",
    disruption: "கனமழை கண்டறியப்பட்டது",
    premium: "ஸ்மார்ட் பிரீமியம்",
    update: "பிரீமியம் புதுப்பிக்கவும்",
    trigger: "நிகழ்வு தொடங்கு",
    payout: "உடனடி கட்டணம்",
    awaiting: "காத்திருக்கிறது...",
    credited: "உடனடி சேர்க்கை",
  },

  te: {
    title: "GigShield AI",
    subtitle: "AI ఆదాయం రక్షణ",
    protected: "రక్షిత ఆదాయం",
    live: "రక్షణ సక్రియంగా ఉంది",
    monitoring: "రియల్ టైమ్ మానిటరింగ్",
    risk: "ప్రమాద యంత్రం",
    disruption: "భారీ వర్షం గుర్తించబడింది",
    premium: "స్మార్ట్ ప్రీమియం",
    update: "ప్రీమియం నవీకరించండి",
    trigger: "ఈవెంట్ ప్రారంభించండి",
    payout: "తక్షణ చెల్లింపు",
    awaiting: "ఎదురుచూస్తోంది...",
    credited: "తక్షణ జమ",
  },

  bn: {
    title: "GigShield AI",
    subtitle: "AI আয় সুরক্ষা",
    protected: "সুরক্ষিত আয়",
    live: "সুরক্ষা সক্রিয়",
    monitoring: "রিয়েল-টাইম পর্যবেক্ষণ",
    risk: "ঝুঁকি ইঞ্জিন",
    disruption: "ভারী বৃষ্টি সনাক্ত",
    premium: "স্মার্ট প্রিমিয়াম",
    update: "প্রিমিয়াম আপডেট করুন",
    trigger: "ইভেন্ট চালু করুন",
    payout: "তাৎক্ষণিক পেমেন্ট",
    awaiting: "অপেক্ষা করছে...",
    credited: "তাৎক্ষণিক জমা",
  },

  gu: {
    title: "GigShield AI",
    subtitle: "AI આવક સુરક્ષા",
    protected: "સુરક્ષિત આવક",
    live: "સુરક્ષા સક્રિય",
    monitoring: "રિયલ ટાઈમ મોનીટરીંગ",
    risk: "જોખમ એન્જિન",
    disruption: "ભારે વરસાદ શોધાયો",
    premium: "સ્માર્ટ પ્રીમિયમ",
    update: "પ્રીમિયમ અપડેટ કરો",
    trigger: "ઇવેન્ટ ટ્રિગર કરો",
    payout: "તાત્કાલિક ચુકવણી",
    awaiting: "રાહ જોઈ રહ્યું છે...",
    credited: "તાત્કાલિક જમા",
  },

  kn: {
    title: "GigShield AI",
    subtitle: "AI ಆದಾಯ ರಕ್ಷಣೆ",
    protected: "ರಕ್ಷಿತ ಆದಾಯ",
    live: "ರಕ್ಷಣೆ ಸಕ್ರಿಯ",
    monitoring: "ರಿಯಲ್-ಟೈಮ್ ಮಾನಿಟರಿಂಗ್",
    risk: "ಅಪಾಯ ಎಂಜಿನ್",
    disruption: "ಭಾರೀ ಮಳೆ ಪತ್ತೆಯಾಗಿದೆ",
    premium: "ಸ್ಮಾರ್ಟ್ ಪ್ರೀಮಿಯಂ",
    update: "ಪ್ರೀಮಿಯಂ ನವೀಕರಿಸಿ",
    trigger: "ಈವೆಂಟ್ ಪ್ರಾರಂಭಿಸಿ",
    payout: "ತಕ್ಷಣದ ಪಾವತಿ",
    awaiting: "ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ...",
    credited: "ತಕ್ಷಣ ಜಮಾ",
  },

  ml: {
    title: "GigShield AI",
    subtitle: "AI വരുമാന സംരക്ഷണം",
    protected: "സംരക്ഷിത വരുമാനം",
    live: "സംരക്ഷണം സജീവമാണ്",
    monitoring: "റിയൽ-ടൈം നിരീക്ഷണം",
    risk: "റിസ്ക് എൻജിൻ",
    disruption: "കനത്ത മഴ കണ്ടെത്തി",
    premium: "സ്മാർട്ട് പ്രീമിയം",
    update: "പ്രീമിയം അപ്ഡേറ്റ് ചെയ്യുക",
    trigger: "ഇവന്റ് ആരംഭിക്കുക",
    payout: "ഉടൻ പേയ്‌മെന്റ്",
    awaiting: "കാത്തിരിക്കുന്നു...",
    credited: "ഉടൻ ക്രെഡിറ്റ്",
  },

  pa: {
    title: "GigShield AI",
    subtitle: "AI ਆਮਦਨ ਸੁਰੱਖਿਆ",
    protected: "ਸੁਰੱਖਿਅਤ ਆਮਦਨ",
    live: "ਸੁਰੱਖਿਆ ਚਾਲੂ ਹੈ",
    monitoring: "ਰੀਅਲ-ਟਾਈਮ ਮਾਨੀਟਰਿੰਗ",
    risk: "ਜੋਖਮ ਇੰਜਨ",
    disruption: "ਭਾਰੀ ਮੀਂਹ ਮਿਲਿਆ",
    premium: "ਸਮਾਰਟ ਪ੍ਰੀਮੀਅਮ",
    update: "ਪ੍ਰੀਮੀਅਮ ਅਪਡੇਟ ਕਰੋ",
    trigger: "ਈਵੈਂਟ ਸ਼ੁਰੂ ਕਰੋ",
    payout: "ਤੁਰੰਤ ਭੁਗਤਾਨ",
    awaiting: "ਉਡੀਕ ਕਰ ਰਹੇ ਹਾਂ...",
    credited: "ਤੁਰੰਤ ਜਮ੍ਹਾਂ",
  },

  ur: {
    title: "GigShield AI",
    subtitle: "AI آمدنی تحفظ",
    protected: "محفوظ آمدنی",
    live: "تحفظ فعال ہے",
    monitoring: "ریئل ٹائم مانیٹرنگ",
    risk: "خطرہ انجن",
    disruption: "شدید بارش کا پتہ چلا",
    premium: "سمارٹ پریمیم",
    update: "پریمیم اپڈیٹ کریں",
    trigger: "ایونٹ شروع کریں",
    payout: "فوری ادائیگی",
    awaiting: "انتظار ہو رہا ہے...",
    credited: "فوری جمع",
  }
};